#!/bin/bash
#
#####################################################################
MAVEN="/usr/bin/mvn"
WORKING_DIR=`pwd`

#####################################################################

RETVAL="0"

# See how we were called.
function dev2() {
  $MAVEN -Pdev clean install -DskipTests=true -l out/dev2.build.log
}

function qa() {
  $MAVEN -Padiqa clean install -DskipTests=true -l out/qa.build.log
}

function prod() {
  $MAVEN -Pproduction clean install -DskipTests=true -l out/prod.build.log
}


function clean() {
  if [ -d $CATALINA_HOME/webapps/adidasweb ]; then
    \rm -r $CATALINA_HOME/webapps/adidasweb
  fi
  $MAVEN -Parvlocal clean -DskipTests=true
}

function compile() {
  $MAVEN -Parvlocal clean install -DskipTests=true
}

function unitTests() {
  $MAVEN clean install
}

function all() {
  if [ -d $CATALINA_HOME/webapps/adidasweb ]; then
    \rm -r $CATALINA_HOME/webapps/adidasweb
  fi
  $MAVEN -Parvlocal clean install -DskipTests=true
  echo "----------------------------------------------------------------------"
  echo "Copying target artifact to Tomcat"
  cp $WORKING_DIR/adidasweb/target/adidasweb.war $CATALINA_HOME/webapps
  cp -r $WORKING_DIR/adidasweb/target/adidasweb $CATALINA_HOME/webapps/adidasweb
  echo "----------------------------------------------------------------------"
  ls -alwG $CATALINA_HOME/webapps | grep 'war'
}

function mvnRedeploy() {
  $MAVEN -Parvlocal -e tomcat:redeploy -DskipTests=true
}

function version() {
  $MAVEN --version
}

function start() {
  $CATALINA_HOME/bin/catalina.sh run >> $CATALINA_HOME/logs/apps/adidasWeb.log &
}
function stop() {
  $CATALINA_HOME/bin/catalina.sh stop
}

function usage()
{
  echo "Usage: build.sh ( commands ... )"
  echo "commands:"
  echo "  dev2              Clean/install of artifacts for DEV2"
  echo "  qa                Clean/install of artifacts for QA"
  echo "  prod              Clean/install of artifacts for PRODUCTION"
  echo "  clean             Clean of artifacts for ARVLOCAL"
  echo "  compile           Clean/install of artifacts for ARVLOCAL"
  echo "  unit              Clean/install for unit tests"
  echo "  all               Clean, rebuild and then deploy artifacts to Tomcat local directory"
  echo "  start             Start adidas web on Tomcat"
  echo "  stop              Stop  adidas web on Tomcat"
  echo "  version           What version of ant and/or maven are you running?"
  exit 1
}

# See how we were called.
RETVAL="0"
case "$1" in
  dev2)
    dev2
    ;;
  qa)
    qa
    ;;
  prod)
    prod
    ;;
  clean)
    clean
    ;;
  compile)
    compile
    ;;
  unit)
    unitTests
    ;;
  version)
    version
    ;;
  start)
    start
    ;;
  stop)
    stop
    ;;
  all)
    all
    ;;
  *)
    usage
    ;;
esac

exit $RETVAL

