# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

PATH=.:$PATH:$HOME/bin

export PATH

ORACLE_SID=ORCL; export ORACLE_SID
ORACLE_HOSTNAME=o16-112.localdomain; export ORACLE_HOSTNAME
ORACLE_UNQNAME=ORCL; export ORACLE_UNQNAME

ORACLE_BASE=/u01/app/oracle; export ORACLE_BASE
ORACLE_HOME=$ORACLE_BASE/product/11.2.0/db_1; export ORACLE_HOME
PATH=$ORACLE_HOME/bin:$PATH; export PATH

ORACLE_IC_HOME=$ORACLE_HOME; export ORACLE_IC_HOME
TNS_ADMIN=$ORACLE_IC_HOME
DYLD_LIBRARY_PATH=$ORACLE_IC_HOME
LD_LIBRARY_PATH=/usr/lib/oracle/11.2/client/lib:
CLASSPATH=$ORACLE_HOME/owb/wf/lib/ojdbc14.jar:./
export TNS_ADMIN PATH DYLD_LIBRARY_PATH LD_LIBRARY_PATH CLASSPATH
